AWSTemplateFormatVersion: 2010-09-09
Description: create ec2 instance in default vpc and allow http acees

Parameters: 
  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources: 
  appSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow http access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: app-security-group 
    
  iamInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - S3DynamoDBFullAccessRole 
    

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: ukey
      ImageId: !Ref AmazonLinuxAMIID
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref appSecurityGroup
      IamInstanceProfile: !Ref iamInstanceProfile 
      UserData: !Base64 | 
        #!/bin/bash -ex
        wget https://aws-tc-largeobjects.s3-us-west-2.amazonaws.com/DEV-AWS-MO-GCNv2/FlaskApp.zip
        unzip FlaskApp.zip
        cd FlaskApp/
        yum -y install python3 mysql
        pip3 install -r requirements.txt
        amazon-linux-extras install epel
        yum -y install stress
        export PHOTOS_BUCKET=${SUB_PHOTOS_BUCKET}
        export AWS_DEFAULT_REGION=us-west-2
        export DYNAMO_MODE=on
        FLASK_APP=application.py /usr/local/bin/flask run --host=0.0.0.0 --port=80
      Tags:
        - Key: Name
          Value: employee-directory-app
