AWSTemplateFormatVersion: 2010-09-09
Description: Set up VPC with flow logs  
            peace out 


Resources:

###########
# VPC with Internet Gateway
########### 

  LabVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Lab VPC

  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: lab-vpc-flow-log
      RetentionInDays: 14 

  CFlowLog:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      LogDestinationType: cloud-watch-logs 
      DeliverLogsPermissionArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/VPCFlowLogsRole'
      LogGroupName: !Ref LogGroup 
      ResourceId: !Ref LabVPC
      ResourceType: 'VPC'
      TrafficType: REJECT 