AWSTemplateFormatVersion: 2010-09-09
Description: Challenge lab template

Parameters: 

  VpcCidr:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCidr:
    Type: String
    Default: 10.0.0.0/24

  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/23

  AmazonLinuxAMIID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources: 

  ###########
  # VPC with Internet Gateway
  ###########

  ChallengeVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Challenge VPC 

  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Challenge IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn:
      - IGW
      - ChallengeVPC
    Properties:
      VpcId: !Ref ChallengeVPC
      InternetGatewayId: !Ref IGW

  ###########
  # Security Group
  ###########
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    DependsOn: ChallengeVPC
    Properties:
      GroupName: ChallengeSG
      GroupDescription: Enable access to SSH
      VpcId: !Ref ChallengeVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: ChallengeSG 

  ###########
  # Private Subnet
  ###########
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    DependsOn: ChallengeVPC
    Properties:
      AvailabilityZone: !Select 
        - 0
        - !GetAZs 
          Ref: AWS::Region 
      VpcId: !Ref ChallengeVPC 
      CidrBlock: !Ref PrivateSubnetCidr
      Tags:
        - Key: Name
          Value: Private Subnet 

  ###########
  # EC2 Instance
  ###########
  ChallengeInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmazonLinuxAMIID
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref SecurityGroup 
      SubnetId: !Ref PrivateSubnet
      Tags:
        - Key: Name
          Value: Challenge Instance